version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.1-management
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "127.0.0.1:5672:5672"  # AMQP protocol port
      - "127.0.0.1:15672:15672"  # Management UI port
      - "127.0.0.1:1883:1883"  # MQTT protocol port
      - "127.0.0.1:15675:15675"  # MQTT over WebSockets port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt && rabbitmq-server"
    restart: always

volumes:
  rabbitmq_data:
